name: Testnet deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M')"

      - name: Get the current version ref
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          NODE_OPTIONS: --max-old-space-size=6144
          CI: false

          VITE_API_URL: ${{ secrets.API_URL }}
          VITE_WEBSOCKET_URL: ${{ secrets.WEBSOCKET_URL }}
          VITE_DONATION_ADDRESS: ${{ secrets.DONATION_ADDRESS }}
          VITE_NETWORK: mumbai
          VITE_ACCOUNT_MINTER_CONTRACT: "0x6918C16938095E6247dC3B552B4b14f553be06D4"
          VITE_SESSION_CONTRACT: "0x4d3987a15b981645544fE8133B1e40A177c19760"
          VITE_FARM_CONTRACT: "0xa6c6bbF5C772916bB39D13D972da9f9CE3E9f369"
          VITE_INVENTORY_CONTRACT: "0x9b78DFb31a3fab4A23F12e4CA6D85C3fEA5E8136"
          VITE_TOKEN_CONTRACT: "0xdD0cdB13D62aADdc6A9F19f836Aaaa32E07f4d04"
          VITE_WISHING_WELL_CONTRACT: "0xbDBB736FC2Ce2b7aEE88e5f86888Cef7414Ad1F5"
          VITE_PAIR_CONTRACT: "0xaE42EA9864C36820627068a11959915f817ce809"
          VITE_TRADER_CONTRACT: "0x123d310FE94FcbA7Ca9a33A3965e2938A7Ac84B8"
          VITE_TREASURY_ADDRESS: "0x1DB57407EE80709D4d862fe81399FBB35B8B9586"
          VITE_BUMPKIN_DETAILS_CONTRACT: "0xAeB15F2aE9f248bf6a3606fadA02EF79f35c8bEF"
          VITE_BUMPKIN_ITEMS_CONTRACT: "0xa163b82370DeBb82C12B735b995a332D50a02252"
          VITE_BUMPKIN_CONTRACT: "0x48f53e506882a502b07668f6990f0e15422a539b"
          VITE_DISCORD_REDIRECT: "https://sunflower-land.com/testnet/"
          VITE_CLIENT_VERSION: ${{ steps.date.outputs.date }}
          VITE_RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
          VITE_RECAPTCHA_SITEKEY: "6Lfqm6MeAAAAAFS5a0vwAfTGUwnlNoHziyIlOl1s"
          VITE_CLOUDFLARE_CAPTCHA_SITEKEY: "0x4AAAAAAAAoHFfoj3YbRYSO"
          VITE_FROG_CONTRACT: "0x52A5ddFF59E0A27a1cBA75c8045A434b7D296A6c"
          VITE_FROG_DONATION: "0x1AFad0B5A0D532c9123A5f2F879A421413B5b6f7"
          VITE_HALLOWEEN_CONTRACT: "0xE123a99A5343C49F74BA372Ca9D3242f02D638ab"
          VITE_TADPOLE_CONTRACT: "0x2c65Dabdeb338188618bc94E2aAD0ddfFa40c1C9"
          VITE_INCUBATOR_CONTRACT: "0xd19b1Ab87D650fc9e9c73F02F6FAe647bcC50c96"
          VITE_WHITELIST_TOKEN_CONTRACT: "0x49c37423A304A07d9b51748aF86Fe16BA64d972E"
          VITE_QUEST_CONTRACT: "0x842695E88dB4143281AA4617017baFaB74Fb5Ee1"
          VITE_EASTER_EGG_CONTRACT: "0x52668ebcFE522424F95c26b206cB545513588268"
          VITE_SEAL_CONTRACT: "0x23b1aA9382602E929722bA081E00dCdEb883482d"
          VITE_BUY_SFL_CONTRACT: "0xe4A579BAEEB8cE727937f2AE6dca9334f0a8C1A1"
          VITE_LOST_AND_FOUND_CONTRACT: "0x87076D016dc711a8b099dD1A4575634bB5a781D3"
          VITE_DEPOSIT_CONTRACT: "0xcAb9bC3E1d92fA0dACC094c57A412F5271efF562"
          VITE_QUICKSWAP_ROUTER_CONTRACT: "0x0AdFd88E8Bbe16A2E94D833Ae7ebe1dbeb9906F6"
          VITE_WMATIC_CONTRACT: "0x2D2D57e23a1F2bBD22e83Bb018D333cae7f70BBA"
          VITE_GREEDY_GOBLIN_DONATION: "0x7bC6Fe738E5f4FdCbd034489A0320507BCA9806D"
          VITE_CHICKEN_FIGHT_DONATION: "0x99B4E9Dc0b20E4A8a2D5be4145C38196A80e164B"
          VITE_LUNAR_NEW_YEAR_DONATION: "0x871d7970133aad1f98902204e3f27ebfeb959d7c"
          VITE_VALENTINE_EVENT_DONATION: "0xf07bA076A2E327E265e240BB3dd628550fe8d8C1"
          VITE_DAILY_REWARD_CONTRACT: "0x45E4A31E994263a3025325aac63FC15E441A89F5"

          VITE_ALCHEMY_RPC: ${{ secrets.ALCHEMY_RPC }}
          VITE_PRIVATE_IMAGE_URL: "https://sunflower-land.com/testnet-assets"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://sunflower-land.com/testnet --delete

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://www.sunflower-land.com/testnet --delete
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
